### ISSUE TITLE
5.0.0 relies on prereleases 

### ISSUE THREAD

**Issue by connorshea** [redis-store/redis-actionpack#10]
Thanks for releasing 5.0.0 :) I think there was an oversight since the gem spec still relies on prerelease versions of redis-store and redis-rack, though.

**Comment by connorshea** [comment]
Ditto for redis-rack, which doesn't have a final release out yet.

cc: @radar @tubbo

**Comment by tubbo** [comment]
redis-rack needs an earlier version (v1.6.0) in order for redis-actionpack to be released, because v2.0.0 of redis-rack depends on rack v2.0, and I couldn't get the gems to line up to work with rack 2.x. PR #13 should resolve this issue.
