### ISSUE TITLE
Use signed session id in cookies instead of plain text

### ISSUE THREAD

**Issue by tubbo** [redis-store/redis-actionpack#21]
From @cjmao at redis-store/redis-rails#85

Currently the session id is stored as plain text in cookies. Though the chance of a user guessing a valid session id is quite low, it's still possible for a user to set his session to another user's.
By using signed session id (`cookies.signed[:_session_id]`), it won't be possible for a user to guess a valid session id.

**Comment by exadeci** [comment]
Any news on this?

**Comment by tubbo** [comment]
@exadeci working on this now, just waiting for my appraisal PR to pass tests so I know I'm working with a clean build.

**Comment by tubbo** [comment]
released as **v5.2.0.pre**, give it a whirl :)
