### ISSUE TITLE
domain :all is not working.

### ISSUE THREAD

**Issue by ratsbomb** [redis-store/redis-actionpack#7]
I'm using redis_store with domain :all option.
then, I got **no implicit conversion of Symbol into String** errors.

I found related issues [here](https://github.com/redis-store/redis-actionpack/pull/5)
but, It's failure status.

My Environments
Rails 3.2.22
```
Using redis 3.2.1
Using redis-namespace 1.5.2
Using redis-store 1.1.7
Using redis-rack 1.4.4
Using redis-actionpack 3.2.4
Using redis-activesupport 3.2.5
Using redis-rack-cache 1.2.2
Using redis-rails 3.2.4
```

**Comment by radar** [comment]
@ratsbomb Please show the configuration exactly as you're using it.

**Comment by tubbo** [comment]
@ratsbomb let me know if this is still a problem but since there hasn't been any activity in over a year, I'm closing.
